### ISSUE TITLE
iMac21,1 and iMac21,2 support

### ISSUE THREAD

**Issue by Grandboy46** [dora2-iOS/iPwnder32#12]
Hello @dora2-iOS,

Apple released new iMacs with the M1 chip which shipped with MacOS 11.3. The problem is those iMacs can run 11.3 or higher and have only USB-C ports which means it won’t work with this tool. Any way to support USB-C ports with USB-C to USB-A adapters on these new iMacs?

sincerely,

**Comment by dora2-iOS** [comment]
M1 support is as indicated in the README.
