### ISSUE TITLE
macOS 11.3 Support

### ISSUE THREAD

**Issue by Grandboy46** [dora2-iOS/iPwnder32#6]
Hi @dora2-iOS,

Macos 11.3 is close to it’s release but it also breaks iPwnder32. Is it possible to update iPwnder32 to support macOS 11.3 and if it is, can you please update it?

**Comment by dora2-iOS** [comment]
How is it broken? It needs more details.

**Comment by Grandboy46** [comment]
I don’t know but I heard apple broke pwndfu tools on 11.3. That is the reason I asked for it. Can you please test it?

**Comment by Grandboy46** [comment]
If it’s working for you, then no problem.

**Comment by dora2-iOS** [comment]
Not enough detailed information. Please provide them. Close.

**Comment by Grandboy46** [comment]
I will be reuploading the işeye after testing.
