### ISSUE TITLE
Fail to enter pwndfu mode macOS 11.3

### ISSUE THREAD

**Issue by AyyItzRob** [dora2-iOS/iPwnder32#8]
Failing to get iPwnder32 to pwndfu on my iPhone 5s. Using the latest macOS 11.3 public release.
<img width="1224" alt="Screen Shot 2021-05-03 at 2 22 56 AM" src="https://user-images.githubusercontent.com/60681230/116850797-e63bac00-abb6-11eb-8766-158f367c87fb.png">

**Comment by dora2-iOS** [comment]
Please create a bug report based on the template.

**Comment by AyyItzRob** [comment]
> Please create a bug report based on the template.

What do you mean by "based on the template"?

**Comment by dora2-iOS** [comment]
Send it according to the template of the bug report.
